version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  # Backend Service
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local

